### ISSUE TITLE
Support for Python 2?

### ISSUE THREAD

**Issue by pombredanne** [WojciechMula/pyDAWG#3]
Having the C extension build and work on Python 2 would be awesome!

**Comment by WojciechMula** [comment]
I know, but I'm completely run out of spare time. It shame for me that I run few open source libs and I can't find few hours monthly to keep things run. :(

BTW I remember that I had deliberately skipped Py2.x, as Py3 come with new string model and I didn't want to duplicate work. It was a mistake.

**Comment by pombredanne** [comment]
@WojciechMula I think this is fin, not a mistake but a rational choice. Supporting Py2 and Py3 in the same C extension has been known to damage the brain. Eventually Py2 will slowly be subsumed by Py3 at some time. For now I am using the pure Python version with Py2 and this has be OK so far.

**Comment by pombredanne** [comment]
@WojciechMula my mistake: I meant pyahocorasick, not pyDAWG
