### ISSUE TITLE
error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by tanmaythakar4** [WojciechMula/pyDAWG#4]
can you help me with the error: Unable to find vcvarsall.bat
python 3.4
windows
visual studio 2015

**Comment by WojciechMula** [comment]
Hi, did you try to run cmd.exe via Start menu option "Visual Studio command line" (or similar name)? It will set up all environment variables. Then run build inside such cmd line.

You might also find helpful https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/
